global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

scrape_configs:
  - job_name: 'linuxtestsvr'
    static_configs:
      - targets: ['app-host:9100']