---
- name: Ensure specified user is deleted if it exists
  hosts: all
  become: true
  vars: user_to_delete: "{{ ansible_env.USER_TO_DELETE }}"
  
  tasks:
    - name: Fail if the USER_TO_DELETE environment variable is not set
      fail:
        msg: "The environment variable USER_TO_DELETE is not set."
      when: user_to_delete is not defined

    - name: Check if user "{{ user_to_delete }}" exists
      command: id -u {{ user_to_delete }}
      register: user_check
      failed_when: false
      changed_when: false

    - name: Delete user "{{ user_to_delete }}" if it exists
      user:
        name: "{{ user_to_delete }}"
        state: absent
        remove: yes
      when: user_check.rc == 0
