---

- hosts: all
  become: true
  tasks:

  ## Ubuntu && Centos
  - name: install apache && PHP 
    ansible.builtin.package: 
      name:
        - "{{ apache_pkg }}"
        - " {{ php_mod }}"
      state: "latest"
      update_cache: true


