---

- hosts: all
  become: true
  tasks:

  ## Ubuntu && Centos
  - name: install apache2 && PHP 
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: "latest"
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  ## Centos  
  - name: Centos, install httpd and PHP packages  
    dnf: 
      name: 
      - httpd
      - php
      state: "latest"
      update_cache: true
    when: ansible_distribution == "Centos"
