---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: true

  - name: install apache2 && net-tools packages
    apt: 
      name:
        - apache2
        - net-tools
      state: "latest"
  
  - name: add php support for apache2
    apt:
      name:
        - libapache2-mod-php
      state: "latest"