---

- hosts: all
  become: true
  tasks:

  ## Ubuntu
  - name: Ubuntu, install apache2 && net-tools && PHP support packages
    apt: 
      name:
        - apache2
        - libapache2-mod-php
        - net-tools
      state: "latest"
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  ## Centos  
  - name: Centos, install httpd and PHP packages  
    dnf: 
      name: 
      - httpd
      - php
      state: "latest"
      update_cache: true
    when: ansible_distribution == "Centos"
