---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: true

  - name: uninstall apache2 package
    apt: 
      name:
        - apache2
      state: "absent"
  
  - name: remove add php support for apache2
    apt:
      name:
        - libapache2-mod-php
      state: "absent"