---

## All servers tasks
- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (Ubuntu)
    tags:  notalways #Always tag ensures play runs all the time irregardless 
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

# only web servers
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 (Web servers)
    tags: apache,apache2,web
    apt:
      name: apache2
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"


# only web servers
- hosts: web_servers
  become: true
  tasks:

  - name: install nginx (Web servers)
    tags: nginx
    apt:
      name: nginx
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"
  
  - name: copy html file into the server
    tags: website,apache,httpd
    ansible.builtin.copy:
      src: /app/data/ansible-keys/ans/playbooks/files/defaults_sites.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

# Only db servers
- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb packages(Ubuntu)
    tags: ubuntu, mariadb, db
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

# Only file servers
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba, smb
    package:
      name: samba
      state: latest

## ALL Linux
- hosts: all_linux
  become: true
  pre_tasks:

  - name: Pre-checks
    apt:
      autoremove: true
      autoclean: true
    when: ansible_distribution == "Ubuntu"
  
  tasks:
    - name: Install zsh
      tags: zsh,zshell
      package:
        name: zsh
        state: latest

      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: add bravest file to /opt to file_servers
    tags: brave
    ansible.builtin.copy:
      src: ./files/brave.txt
      dest: /opt/bravessss.txt
      mode: 0600
      owner: root
      group: root
