services:
  ubuntu_test:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: tjmash/ubnt:jammy
    container_name: ubnt
    ports:
      - 2222:22
    tty: true
    volumes:
      - ./data:/app/data
    networks:
      - ubnt-net

networks:
  ubnt-net:
    driver: bridge
